### ISSUE TITLE
About server data.

### ISSUE THREAD

**Issue by think2011** [begriffs/angular-paginate-anything#72]
server response data like this：
``` javascript
var backEndData = {
  status: 'success',
  data: [
    {a: 1},
    {a: 2},
   {a: 3}
  ],
  pageCount: 100,
  prePage: 10
}
```
so.. what should I do?

please help me : )

**Comment by begriffs** [comment]
It won't understand that JSON structure. Are you able to change the behavior of the server? This directive is looking for specific a specific response format, described here: https://github.com/begriffs/angular-paginate-anything#what-your-server-needs-to-do

Essentially it uses HTTP itself, rather than a JSON envelope, to annotate the information.

**Comment by think2011** [comment]
ok, i got it, thanks!
