### ISSUE TITLE
At what point in the .NET API code should we set the TotalRecordCount

### ISSUE THREAD

**Issue by NickBehrends** [begriffs/angular-paginate-anything#79]
In the sample code here: https://github.com/begriffs/angular-paginate-anything/wiki/How-To-Configure-ASP.NET-Web-API

The TotalRecordCount is never set, but is required by the code. Upon retrieving that from our database, when and where should we set it in out code to return to the client?

**Comment by begriffs** [comment]
Not sure at first glance. Perhaps @tafs7 knows the answer.

**Comment by tafs7** [comment]
it's been a few months since I looked at this code base, but if the sample doesn't include it, it might be a miss. I took some of this code from a project I was working at the time, and we may not have had the requirement to show total count on the screen, so it may be missing here.

the action filter will enrich the action parameter by injecting the HTTP range header data into the action parameter, so if your client is passing the total count in as part of the request, it will already be set by the model binder - in theory :)

**Comment by NickBehrends** [comment]
Thanks for the reply, I passed it in when the return is started as `pagingModel.TotalRecordCount`

So this:
`return this.PagedPartialContent(data, pagingModel.From, pagingModel.To, pagingModel.TotalRecordCount);`

effectively becomes this:
`return this.PagedPartialContent(data, pagingModel.From, pagingModel.To, data.totalCount);`

Seems to be working great!

**Comment by begriffs** [comment]
@NickBehrends excellent! Would you mind updating the wiki with what you learned?

**Comment by NickBehrends** [comment]
Added. The main problem here is that the total count is required on the first run BUT if your client is returning the total count to the web API (mine isnt for some reason, not a huge deal though) you don't have to query the total count again, rather just pass in what the client gave.

While this is faster the problem is that if records are added or removed they will not be included in the count. We opted to just requery every time, it doesn't create any overhead for us. But for future readers, not querying after the first time (just use an if statement to check if its sent from the client) is an option.
