### ISSUE TITLE
Updating pagination when collection changes via javascript

### ISSUE THREAD

**Issue by mattymess** [begriffs/angular-paginate-anything#86]
We're paginating a list of data and the user has the ability to delete one of the records. We want to update the UI and the pagination information when a user does this. However, since the library relies on headers and information from the backend, I'm not sure how to approach this without reloading the page completely. 

Any ideas?

**Comment by begriffs** [comment]
So let's assume there are four items, and you're paginating three per page. The user is on page one and they see items 1,2,3. The user deletes item 2 and you would like the list to show 1,2,4 right?

The pagination code won't do this for you, but if I recall correctly the pagination is connected to an array in its scope. Your code can update the array by removing item 2, asking the server for the third item, and adding that.

Either that or have the paginator request the page again.

**Comment by umdstu** [comment]
Did you ever make any progress on this? I'm attempting the same thing, although instead of updating the contents of the current page every time 1 is removed, i only want to update once the current page is emptied. At which point it would be updated. For example, say you're on page 3, and you have 'remove' all <X per page> items, I'd imagine gotoPage(currentPage) would be called again, which would in reality load the results from currentPage+1. This works, I think, only if you're updating the backend the same time you're updating the front end (if you remove item 67 from the front end, remove that from the back end collection as well).

I guess I'm trying to figure out how to get the pagination scope so I can call gotoPage(), and can't seem to.

**Comment by begriffs** [comment]
I haven't looked into it, but you could try this

```html
<bgf-pagination
  collection="someVariable"
  url="'http://api.server.com/stuff'"
  reload-page="reloadPage">
</bgf-pagination>
```

Where `reloadPage` is a variable in your current scope. If later on you set it to true that will cause the pagination to reload itself.

**Comment by umdstu** [comment]
Embarrassingly, I was already using that for something else, and I never
made the connection. It works! Thanks Joe.

**Comment by begriffs** [comment]
Awesome, glad that's all it took.
